#! /bin/sh

bspc config border_width        3
bspc config window_gap          20
bspc config top_padding         0
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config split_ratio             0.50
bspc config initial_polarity        second_child
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config click_to_focus          true
bspc config ignore_ewmh_focus       true

bspc config pointer_modifier mod1

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color '#000000'
#bspc config focused_border_color '#525252'
bspc config focused_border_color '#77dd77'
#bspc config focused_border_color '#59d2ff'
bspc config presel_feedback_color '#afcce0'

$HOME/bin/de init $HOME/.config/bspwm/config.json | sh

############################################
# Startup stuff
############################################
# key repeat rate
xset r rate 200 50
# set cursor for root window
xsetroot -cursor_name left_ptr
hsetroot -solid '#404040'

#### Additional programs
kill $(pidof sxhkd)
sxhkd &

killall compton
compton --backend glx --unredir-if-possible --vsync opengl-swc --config $HOME/.config/compton.conf &

killall tint2
tint2 &
